Styling
phelian23/bookstore pull request #4
Opened 2021-12-09 21:49 UTC by phelian23

In this PR
- Styling is added

2021-12-09 21:52 UTC, omar-labana commented
Hi @phelian23, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, where the linters are not passing. Please fix the linter errors.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2021-12-09 22:32 UTC, Emmyn5600 requested changes
Hi @phelian23 

Great work on making the project requirements 👏 
You've done well implementing some of the project requirements, but there are still some which aren't addressed yet, please work on it and ask for another review.


 ## Required Changes ♻️
 
- _Check the comments under the review._

## Optional suggestions

- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-12-09 22:32 UTC, Emmyn5600 commented on src/components/addNew.js
>    };
- [ ] When I clicked on the `add new book` without filling out the title and category, I got this error. please fix it.

![setup-11](https://user-images.githubusercontent.com/55635977/145484992-6ac5ba65-6d26-4089-9e31-18c82a51452e.png)

2021-12-09 22:32 UTC, Emmyn5600 commented on src/styles/addNew.module.css
> +}
- [ ] Let try to match with the design provided.

---------------------I Original

![setup-9](https://user-images.githubusercontent.com/55635977/145485704-e05baa59-64eb-4988-b3be-587d0ec14c29.png)

----------------------| Yours

![setup-12](https://user-images.githubusercontent.com/55635977/145485914-860ac0ef-27fa-494a-8cad-bd84127327a4.png)

2021-12-10 09:47 UTC, Lameck1 approved these changes
Hi, @phelian23,

You've done well working on the concerns of the previous review 👍🏼.
The tasks for this milestone are therefore successfully implemented 💯.

Your project is now complete, you are free to merge this branch :shipit:

Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-10 11:38 UTC, merged